import type { Metadata } from "next";

import { TopNav } from "@/components/TopNav";

export const metadata: Metadata = {
  title: "Terms of Service — DECODING JOBS",
  description: "The rules for using DECODING JOBS, for job seekers, founders, and recruiters.",
};

/**
 * A plain-language terms-of-service baseline. Have it reviewed by counsel
 * before a public, commercial launch.
 */
export default function TermsPage() {
  return (
    <div className="flex h-screen w-screen flex-col overflow-hidden bg-white">
      <TopNav />
      <main className="scroll-thin flex-1 overflow-y-auto bg-gradient-to-b from-green-50/40 to-white">
        <article className="mx-auto max-w-2xl px-5 py-10 sm:py-14">
          <h1 className="text-2xl font-bold tracking-tight text-gray-900">Terms of Service</h1>
          <p className="mt-1.5 text-sm text-gray-400">Last updated: 1 October 2026</p>

          <div className="mt-8 flex flex-col gap-6 text-[13.5px] leading-relaxed text-gray-600">
            <section>
              <h2 className="mb-1.5 text-sm font-bold text-gray-900">Using the service</h2>
              <p>
                DECODING JOBS is a map-based job-discovery tool. You need a working email address to sign in.
                Don&apos;t abuse the service — no scraping, no bulk automation, no posting false or misleading
                company or job information.
              </p>
            </section>

            <section>
              <h2 className="mb-1.5 text-sm font-bold text-gray-900">Listings are not ours</h2>
              <p>
                Job listings come from third-party sources and from companies that list themselves. We do not
                guarantee that a listing is accurate, current, or that a company will respond. Always verify
                details before applying.
              </p>
            </section>

            <section>
              <h2 className="mb-1.5 text-sm font-bold text-gray-900">If you list a company</h2>
              <p>
                You must have authority to represent the company you register — verified by signing in with an
                email at that company&apos;s domain. You are responsible for the roles you post.
              </p>
            </section>

            <section>
              <h2 className="mb-1.5 text-sm font-bold text-gray-900">If you search for candidates</h2>
              <p>
                Candidate data is provided for recruiting purposes only. You agree to use it lawfully, to respect
                candidates&apos; visibility choices, and not to export or resell it.
              </p>
            </section>

            <section>
              <h2 className="mb-1.5 text-sm font-bold text-gray-900">AI features</h2>
              <p>
                Resume scores, rewrites, and interview guidance are generated by a language model and are
                suggestions, not professional advice. Verify anything before relying on it.
              </p>
            </section>

            <section>
              <h2 className="mb-1.5 text-sm font-bold text-gray-900">Ending your use</h2>
              <p>
                You can delete your account at any time from{" "}
                <a href="/profile" className="font-semibold text-green-600 hover:underline">your preferences page</a>.
                We may suspend accounts that break these terms.
              </p>
            </section>
          </div>
        </article>
      </main>
    </div>
  );
}
